Sykj.Web/Areas/Manager/Controllers/DicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sykj.Components;
using Sykj.IServices;

namespace Sykj.Web.Areas.Manager.Controllers
{
    /// <summary>
    /// 字典表
    /// </summary>
    public class DicController : MController
    {
        IDic _dic;

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="dic"></param>
        public DicController(IDic dic)
        {
            _dic = dic;
        }

        /// <summary>
        /// 列表页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 查询数据
        /// </summary>
        /// <param name="page">当前页</param>
        /// <param name="limit">页大小</param>
        /// <param name="keyWords">关键字</param>
        /// <returns></returns>
        public IActionResult List(int page, int limit, string keyWords)
        {
            StringBuilder strWhere = new StringBuilder(" 1=1 ");
            if (!string.IsNullOrWhiteSpace(keyWords))
            {
                strWhere.Append(" AND (Name.Contains(@0)) ");
            }

            var list = _dic.GetPagedList(page, limit, strWhere.ToString(), " Id desc ", keyWords);
            int recordCount = _dic.GetRecordCount(strWhere.ToString(), keyWords);
            return Json(ListResult(list, recordCount));
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            ViewBag.ParentIdAll = BindDropList();
            return View();
        }

        /// <summary>
        /// 添加保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ModelValidation]//服务器表单验证
        public IActionResult Add(Sykj.Entity.Dic model)
        {
            var model1 = _dic.GetModel(c => c.Name == model.Name);
            if (model1 != null)
            {
                return Content("键已存在，请更换后重试！");
            }
            model.CreateDate = DateTime.Now;
            model.UserId = UserId;
            bool b = _dic.Add(model);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit(int id)
        {
            var model = _dic.GetModel(c => c.Id == id);
            if (model == null)
            {
                return Content("查询不到数据！");
            }
            ViewBag.ParentIdAll = BindDropList();
            return View(model);
        }

        /// <summary>
        /// 编辑保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ModelValidation]//服务器表单验证
        public IActionResult Edit(Sykj.Entity.Dic dic)
        {
            var model = _dic.GetModel(c => c.Id == dic.Id);
            if (model == null)
            {
                return Json(Failed("查询不到该数据"));
            }
            model.Name = dic.Name;
            model.ParentId = dic.ParentId;
            model.Value = dic.Value;
            model.Types = dic.Types;
            model.Remark = dic.Remark;
            bool b = _dic.Update(model);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DeleteAll(List<int> ids)
        {
            var list = _dic.GetList(c => ids.Contains(c.Id));
            bool b = _dic.Delete(list);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 绑定下拉列表信息
        /// </summary>
        public List<SelectListItem> BindDropList()
        {
            List<SelectListItem> itemList = new List<SelectListItem>();
            itemList.Add(new SelectListItem { Text = "请选择父级", Value = "0" });

            var listAll = _dic.GetList().ToList();
            if (listAll.Count > 0)
            {
                var listOne = listAll.Where(c => c.ParentId == 0);
                SelectListItem selectItem;
                foreach (var item in listOne)
                {
                    string text = item.Value;
                    text = "╋" + text;
                    selectItem = new SelectListItem
                    {
                        Text = text,
                        Value = item.Id.ToString()
                    };
                    string blank = "├";
                    itemList.Add(selectItem);

                    BiudTree(item.Id, itemList, listAll, blank);
                }
            }
            return itemList;
        }

        /// <summary>
        /// 递归查询，绑定select
        /// </summary>
        /// <param name="pId"></param>
        /// <param name="itemList"></param>
        /// <param name="dataList"></param>
        /// <param name="blank"></param>
        private void BiudTree(int pId, List<SelectListItem> itemList, List<Entity.Dic> dataList, string blank)
        {
            var list = dataList.Where(c => c.ParentId == pId);
            SelectListItem selectItem;
            foreach (var item in list)
            {
                string text = item.Value;
                text = blank + "『" + text + "』";

                selectItem = new SelectListItem
                {
                    Text = text,
                    Value = item.Id.ToString()
                };

                itemList.Add(selectItem);
                string blank2 = blank + "─";
                BiudTree(item.Id, itemList, dataList, blank2);
            }
        }
    }
}

Sykj.Web/Areas/Manager/Views/Dic/Add.cshtml
@{
    ViewData["Title"] = "添加字典表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<div class="layui-bg">
    <form class="layui-form" style="padding: 20px 30px 0 0;" method="post">
        <div class="layui-form-item">
            <label class="layui-form-label">键</label>
            <div class="layui-input-block">
                <input type="text" name="Name" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">父级</label>
            <div class="layui-input-block">
                <select id="ParentId" name="ParentId" asp-items="@ViewBag.ParentIdAll"></select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">值</label>
            <div class="layui-input-block">
                <input type="text" name="Value" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">业务分类</label>
            <div class="layui-input-block">
                <input type="text" name="Types" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">标识</label>
            <div class="layui-input-block">
                <input type="text" name="Signs" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <input type="text" name="Remark" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="add" id="submit" type="button">提交</button>
                <button id="close" type="button" class="layui-btn layui-btn-primary">关闭</button>
            </div>
        </div>
    </form>
</div>
@section scriptsfeet
{
    <script type="text/javascript">
    layui.config({
        base: '/layuiadmin/' //静态资源所在路径;
    }).use(['form','sykjwh'], function () {

        var $ = layui.$,form = layui.form,sykjwh = layui.sykjwh;

        $("#close").click(function () {
            sykjwh.close();
        });

        //表单提交
        form.on('submit(add)', function (obj) {
            sykjwh.save('@Url.Action("add", "Dic", new { area = Constant.AREAMANAGER })', obj.field);
        });
    });
    </script>
}

Sykj.Web/Areas/Manager/Views/Dic/Edit.cshtml
@{
    ViewData["Title"] = "编辑字典表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
@model Sykj.Entity.Dic
<div class="layui-bg">
    <form class="layui-form" style="padding: 20px 30px 0 0;" method="post">
        <div class="layui-form-item">
            <label class="layui-form-label">键</label>
            <div class="layui-input-block">
                <input type="text" asp-for="Name" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">父级</label>
            <div class="layui-input-block">
                <select id="ParentId" name="ParentId" asp-items="@ViewBag.ParentIdAll" asp-for="ParentId"></select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">值</label>
            <div class="layui-input-block">
                <input type="text" asp-for="Value" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">业务分类</label>
            <div class="layui-input-block">
                <input type="text" asp-for="Types" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">标识</label>
            <div class="layui-input-block">
                <input type="text" asp-for="Signs" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <input type="text" asp-for="Remark" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="edit" id="submit" type="button">提交</button>
                <button id="close" type="button" class="layui-btn layui-btn-primary">关闭</button>
            </div>
        </div>
    </form>
</div>
@section scriptsfeet
{
    <script type="text/javascript">
    layui.config({
        base: '/layuiadmin/' //静态资源所在路径;
    }).use(['form','sykjwh'], function () {

        var $ = layui.$,form = layui.form,sykjwh = layui.sykjwh;

        $("#close").click(function () {
            sykjwh.close();
        });

        //表单提交
        form.on('submit(edit)', function (obj) {
            sykjwh.save('@Url.Action("edit", "Dic", new { area = Constant.AREAMANAGER })', obj.field);
        });
    });
    </script>
}

Sykj.Web/Areas/Manager/Views/Dic/Index.cshtml
@{
    ViewData["Title"] = "字典表列表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">字典表</div>
                <div class="layui-card-body">
                    <div class="layui-row">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <input type="text" id="keyWords" name="keyWords" placeholder="请输入关键字" autocomplete="off" class="layui-input">
                                <span class="input-group-btn">
                                    <button class="layui-btn" id="search">
                                        <i class="layui-icon layui-icon-search"></i>
                                    </button>
                                </span>
                            </div>                            
                        </div>
                    </div>
                    <div class="layui-row">
                        <div class="layui-btn-container">
                            <div class="layui-btn-group">
                                <button class="layui-btn layui-btn-sm" id="add"><i class="layui-icon">&#xe654;</i>增加</button>
                                <button class="layui-btn layui-btn-sm layui-btn-danger" id="deleteAll"><i class="layui-icon">&#xe640;</i>删除</button>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <table class="layui-table" lay-data="{page:true, id:'list'}" lay-filter="list">
                            <thead>
                                <tr>
                                    <th lay-data="{checkbox:true, fixed: true}"></th>
                                    <th lay-data="{ field: 'id'}">ID</th>
		                            <th lay-data="{ field: 'name'}">键</th>
		                            <th lay-data="{ field: 'parentId'}">父级ID</th>
		                            <th lay-data="{ field: 'value'}">值</th>
		                            <th lay-data="{ field: 'types'}">业务分类</th>
		                            <th lay-data="{ field: 'createDate'}">创建日期</th>
		                            <th lay-data="{ field: 'createUserName'}">创建人</th>
		                            <th lay-data="{ field: 'signs'}">标识</th>
		                            <th lay-data="{ field: 'remark'}">备注</th>
                                    <th lay-data="{toolbar:'#tableoption',fixed:'right'}">操作</th>
                                </tr>
                            </thead>
                        </table>
                        <script type="text/html" id="tableoption">
                            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scriptsfeet
{
<script type="text/javascript">
        layui.config({
            base: '/layuiadmin/' //自定义模块路径
        }).use(['sykjwh', 'table'], function () {
            var $ = layui.$, sykjwh = layui.sykjwh, table = layui.table;

            //绑定数据
            sykjwh.dataBind('@Url.Action("list", "Dic", new { area = Constant.AREAMANAGER })');

            //添加
            $("#add").click(function () {
                sykjwh.open('添加字典表', '@Url.Action("add", "Dic", new { area = Constant.AREAMANAGER })', 700, 460);
            });

            //批量删除
            $("#deleteAll").click(function () {
                sykjwh.batOperate('@Url.Action("deleteall", "Dic", new { area = Constant.AREAMANAGER })', 'id');
            });

            //监听表格行
            table.on('tool(list)', function (obj) {
                var data = obj.data;//获得当前行数据
                if (obj.event === 'edit') {
                    sykjwh.open('编辑字典表', '@Url.Action("edit", "Dic", new { area = Constant.AREAMANAGER })/' + data.id, 700, 460);
                }
            });

            //搜索
            $("#search").click(function () {
                //绑定数据
                sykjwh.dataBind('@Url.Action("list", "Dic", new { area = Constant.AREAMANAGER })', {
                    keyWords: $.trim($("#keyWords").val())
                });
            });
        });
</script>
}