Sykj.Web/Areas/Manager/Controllers/GuestbookController.cs
/*
*┌──────────────────────────────────────────────────────────────┐
*│　描    述：                                                    
*│　作    者：bjg                                            
*│　版    本：1.0    模板代码自动生成                                                
*│　创建时间：2019-02-20 11:49:48       
*│  公    司：云南尚雅科技文化有限公司
*└──────────────────────────────────────────────────────────────┘
*┌──────────────────────────────────────────────────────────────┐
*│　命名空间： Sykj.Web.Areas.Manager.Controllers                         
*│　类    名： GuestbookController                                 
*└──────────────────────────────────────────────────────────────┘
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Sykj.Components;
using Sykj.IServices;

namespace Sykj.Web.Areas.Manager.Controllers
{
    /// <summary>
    /// 留言
    /// </summary>
    public class GuestbookController : MController
    {
        IGuestbook _guestbook;
        IUsers _users;

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="guestbook">留言表</param>
        /// <param name="users">用户表</param>
        public GuestbookController(IGuestbook guestbook, IUsers users)
        {
            _guestbook = guestbook;
            _users = users;
        }

        /// <summary>
        /// 列表页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 查询数据
        /// </summary>
        /// <param name="page">当前页</param>
        /// <param name="limit">页大小</param>
        /// <param name="keyWords">关键字</param>
        /// <returns></returns>
        public IActionResult List(int page, int limit, string keyWords)
        {
            StringBuilder strWhere = new StringBuilder(" 1=1 ");
            if (!string.IsNullOrWhiteSpace(keyWords))
            {
                strWhere.Append(" AND (NickName.Contains(@0) OR Description.Contains(@0) )");
            }

            var list = _guestbook.GetPagedList(page, limit, strWhere.ToString(), " Id desc ", keyWords);

            int recordCount = _guestbook.GetRecordCount(strWhere.ToString(), keyWords);
            return Json(ListResult(list, recordCount));
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit(int id)
        {
            var model = _guestbook.GetModel(c => c.Id == id);
            if (model == null)
            {
                return Content("查询不到数据！");
            }
            return View(model);
        }

        /// <summary>
        /// 编辑保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ModelValidation]//服务器表单验证
        public IActionResult Edit(Sykj.Entity.Guestbook guestbook)
        {
            var model = _guestbook.GetModel(c => c.Id == guestbook.Id);
            if (model == null)
            {
                return Json(Failed("查询不到该数据"));
            }
            model.ReplyDescription = guestbook.ReplyDescription;
            model.Status = 1;
            model.HandlerDate = DateTime.Now;
            model.HandlerUserId = UserId;
            model.HandlerNickName = _users.GetModel(x => x.UserId == UserId).NickName??"管理员";
            bool b = _guestbook.Update(model);
            Components.LogOperate.Add("回复留言", "回复ID为【" + guestbook.Id + "】的留言", HttpContext);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DeleteAll(List<int> ids)
        {
            var list = _guestbook.GetList(c => ids.Contains(c.Id));
            bool b = _guestbook.Delete(list);
            Components.LogOperate.Add("批量删除留言", "删除ID为【" + string.Join(",", ids) + "】的留言", HttpContext);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 审核通过
        /// </summary>
        /// <returns></returns>
        public IActionResult GuestBookAudit(List<int> ids)
        {
            var list = _guestbook.GetList(c => ids.Contains(c.Id)).ToList();
            list.ForEach(c => c.AuditStatus = 1);
            bool b = _guestbook.UpdateRange(list);
            Components.LogOperate.Add("批量审核留言", "审核ID为【" + string.Join(",", ids) + "】的留言", HttpContext);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult GuestBookNoAudit(List<int> ids)
        {
            var list = _guestbook.GetList(c => ids.Contains(c.Id)).ToList();
            list.ForEach(c => c.Status = 0);
            bool b = _guestbook.UpdateRange(list);
            Components.LogOperate.Add("批量设置未处理留言", "设置ID为【" + string.Join(",", ids) + "】的留言为未处理留言", HttpContext);
            return Json(AjaxResult(b));
        }
    }
}

Sykj.Web/Areas/Manager/Views/Guestbook/Edit.cshtml
@{
    ViewData["Title"] = "编辑";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
@model Sykj.Entity.Guestbook
<div class="layui-bgn">
    <form class="layui-form" style="padding: 20px 30px 0 0;" method="post">
        <div class="layui-form-item">
            <label class="layui-form-label">留言内容</label>
            <div class="layui-col-xs9">
                <textarea placeholder="请输入内容" asp-for="Description" class="layui-textarea"></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">留言时间</label>
            <div class="layui-col-xs9">
                <input type="text" asp-for="CreatedDate" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">回复内容</label>
            <div class="layui-col-xs9">
                <textarea placeholder="请输入内容" asp-for="ReplyDescription" class="layui-textarea" lay-verify="required"></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-col-xs3"></div>
            <div class="layui-col-xs4">
                <button class="layui-btn" lay-submit lay-filter="edit" id="submit" type="button">提交</button>
                <button id="close" type="button" class="layui-btn layui-btn-primary">关闭</button>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-col-xs3"></div>
        </div>
    </form>
</div>
@section scriptsfeet
    {
    <script type="text/javascript">
    layui.config({
        base: '/layuiadmin/' //静态资源所在路径;
    }).use(['form','sykjwh'], function () {

        var $ = layui.$,form = layui.form,sykjwh = layui.sykjwh;

        $("#close").click(function () {
            sykjwh.close();
        });

        //表单提交
        form.on('submit(edit)', function (obj) {
            sykjwh.save('@Url.Action("edit", "Guestbook", new { area = Constant.AREAMANAGER })', obj.field);
        });
    });
    </script>
}

Sykj.Web/Areas/Manager/Views/Guestbook/Index.cshtml
@{
    ViewData["Title"] = "列表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">留言管理</div>
                <div class="layui-card-body">
                    <div class="layui-row">
                        <div class="layui-form-item">
                            <div class="layui-col-md3" style="padding-left:0">
                                <div class="input-group">
                                    <input type="text" id="keyWords" name="keyWords" placeholder="请输入要搜索的问题" autocomplete="off" class="layui-input">
                                    <span class="input-group-btn">
                                        <button class="layui-btn" id="search">
                                            <i class="layui-icon layui-icon-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <div class="layui-btn-container">
                            <div class="layui-btn-group">
                                <button class="layui-btn layui-btn-sm layui-btn-danger" id="deleteAll"><i class="layui-icon">&#xe640;</i>删除</button>
                                <button class="layui-btn layui-btn-sm  layui-bg-orange" id="audit"><i class="layui-icon">&#xe640;</i>审核通过</button>
                                <button class="layui-btn  layui-btn-sm layui-bg-blue" id="noAudit"><i class="layui-icon">&#xe640;</i>审核不通过</button>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <table class="layui-table" lay-data="{page:true, id:'list'}" lay-filter="list">
                            <thead>
                                <tr>
                                    <th lay-data="{checkbox:true, fixed: true}"></th>
                                    <th lay-data="{ field: 'nickName',width:150}">留言者</th>
                                    <th lay-data="{ field: 'description',width:300}">留言内容</th>
                                    <th lay-data="{ field: 'createdDate',width:200}">留言时间</th>
                                    <th lay-data="{ field: 'handlerNickName',width:150}">处理人</th>
                                    <th lay-data="{ field: 'handlerDate',width:200}">处理时间</th>
                                    <th lay-data="{ field: 'replyDescription',width:200}">回复内容</th>
                                    <th lay-data="{ field: 'auditStatus',templet: '#auditstatus',width:120}">审核状态</th>
                                    <th lay-data="{ field: 'status',templet: '#state',width:120}">回复状态</th>
                                    <th lay-data="{toolbar:'#tableoption', fixed: 'right',width:90}">操作</th>
                                </tr>
                            </thead>
                        </table>
                        <script type="text/html" id="tableoption">
                            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>回复</a>
                        </script>
                        <script type="text/html" id="state">
                            {{# if(d.status === 0){ }}
                            <span class="layui-badge layui-bg-orange">未处理</span>
                            {{# }else{ }}
                            <span class="layui-badge layui-bg-green">已处理</span>
                            {{# } }}
                        </script>
                        <script type="text/html" id="auditstatus">
                            {{# if(d.auditStatus === 1){ }}
                            <span class="layui-badge layui-bg-orange">通过</span>
                            {{# }else{ }}
                            <span class="layui-badge layui-bg-green">未通过</span>
                            {{# } }}
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scriptsfeet
    {
    <script type="text/javascript">
        layui.config({
            base: '/layuiadmin/' //自定义模块路径
        }).use(['sykjwh', 'table'], function () {
            var $ = layui.$, sykjwh = layui.sykjwh, table = layui.table;

            //绑定数据
            sykjwh.dataBind('@Url.Action("list", "Guestbook", new { area = Constant.AREAMANAGER })');

           //审核通过
            $("#audit").click(function () {
                sykjwh.batOperate('@Url.Action("Guestbookaudit", "Guestbook", new {area = Constant.AREAMANAGER})', 'id');
            });

             //审核不通过
            $("#noAudit").click(function () {
                sykjwh.batOperate('@Url.Action("Guestbooknoaudit", "Guestbook", new {area = Constant.AREAMANAGER})', 'id');
            });

            //批量删除
            $("#deleteAll").click(function () {
                sykjwh.batOperate('@Url.Action("deleteall", "Guestbook", new { area = Constant.AREAMANAGER })', 'id');
            });

            //监听表格行
            table.on('tool(list)', function (obj) {
                var data = obj.data;//获得当前行数据
                if (obj.event === 'edit') {
                    sykjwh.open('编辑', '@Url.Action("edit", "Guestbook", new { area = Constant.AREAMANAGER })/' + data.id, 700, 400);
                }
            });

            //搜索
            $("#search").click(function () {
                //绑定数据
                sykjwh.dataBind('@Url.Action("list", "Guestbook", new { area = Constant.AREAMANAGER })', {
                    keyWords: $.trim($("#keyWords").val())
                });
            });
        });
    </script>
}