Sykj.Web/Areas/Manager/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sykj.IServices;
using System.Text;
using Sykj.Components;

namespace Sykj.Web.Areas.Manager.Controllers
{
    /// <summary>
    /// 会员管理
    /// </summary>
    public class MemberController : MController
    {
        IUsers _users;
        IUserMember _usersMember;
        IPointsDetail _pointsDetail;

       /// <summary>
       /// 
       /// </summary>
       /// <param name="users"></param>
       /// <param name="usersMember"></param>
       /// <param name="pointsDetail"></param>
        public MemberController(IUsers users, IUserMember usersMember, IPointsDetail pointsDetail)
        {
            _users = users;
            _usersMember = usersMember;
            _pointsDetail = pointsDetail;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 绑定数据
        /// </summary>
        /// <param name="page"></param>
        /// <param name="limit"></param>
        /// <param name="keyWords"></param>
        /// <returns></returns>
        public IActionResult List(int page,int limit,string keyWords)
        {
            StringBuilder strWhere = new StringBuilder(" 1=1 ");
            if (!string.IsNullOrWhiteSpace(keyWords))
            {
                strWhere.Append(" AND (UserName.Contains(@0) OR TrueName.Contains(@0))");
            }

            var list = _usersMember.GetMemberList(page, limit, strWhere.ToString(), " UserId desc ", keyWords);
            int recordCount = _usersMember.GetMemberRecordCount(strWhere.ToString(), keyWords);
            return Json(ListResult(list, recordCount));
        }

        /// <summary>
        /// 编辑性别
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="sex"></param>
        /// <returns></returns>
        public IActionResult SexEdit(int userId, string sex)
        {
            var model = _usersMember.GetModel(c => c.UserId == userId);
            if (model == null)
            {
                return Json(Failed("不存在该用户"));
            }
            if (string.IsNullOrWhiteSpace(sex))
            {
                return Json(Failed("修改失败，性别信息为空"));
            }
            Sykj.Entity.Users user = new Entity.Users()
            {
                UserId = userId,
                Sex = sex
            };
            bool b = _users.Update(user, true, c => c.Sex);
            Components.LogOperate.Add("修改会员性别", "修改ID为【" + userId + "】的性别为【"+sex+"】", HttpContext);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 批量启用
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult StartUsing(List<int> ids)
        {
            bool b=false;
            foreach (var id in ids)
            {
                var model = new Sykj.Entity.Users()
                {
                    UserId = id,
                    Activity = true
                };
                b= _users.Update(model, true, c => c.Activity);
            }
            Components.LogOperate.Add("批量启用会员", "启用ID为【" + string.Join(",", ids) + "】的会员", HttpContext);
            return Json(AjaxResult(b));
        }

        /// <summary>
        /// 批量禁用
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Forbidden(List<int> ids)
        {
            bool b = false;
            foreach (var id in ids)
            {
                var model = new Sykj.Entity.Users()
                {
                    UserId = id,
                    Activity = false
                };
                b = _users.Update(model, true, c => c.Activity);
            }
            Components.LogOperate.Add("批量禁用会员", "禁用ID为【" + string.Join(",", ids) + "】的会员", HttpContext);
            return Json(AjaxResult(b));
        }
        
        /// <summary>
        /// 查看详情视图
        /// </summary>
        /// <param name="id">会员id</param>
        /// <returns></returns>
        public IActionResult Info(int id)
        {
            var model = _usersMember.GetMemberModel(c => c.UserId == id);
            if (model == null)
            {
                return Content("查询不到数据！");
            }
            return View(model);
        }

        /// <summary>
        /// 列表页
        /// </summary>
        /// <returns></returns>
        public IActionResult PointsDetail()
        {
            return View();
        }

        /// <summary>
        /// 查询数据
        /// </summary>
        /// <param name="page"></param>
        /// <param name="limit"></param>
        /// <param name="keyWords"></param>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <returns></returns>
        public IActionResult PointsDetailList(int page, int limit, string keyWords,DateTime start,DateTime end)
        {
            StringBuilder strWhere = new StringBuilder(" 1=1 ");
            if (!string.IsNullOrWhiteSpace(keyWords))
            {
                strWhere.Append(" AND Description.Contains(@0)) ");
            }
            if (start != DateTime.MinValue)
            {
                strWhere.Append(" AND CreatedDate>=@1 ");
            }
            if (end != DateTime.MinValue)
            {
                strWhere.Append(" AND CreatedDate<=@2 ");
            }
            var list = _pointsDetail.GetPagedList(page, limit, strWhere.ToString(), " PointId desc ", keyWords,start,end);
            int recordCount = _pointsDetail.GetRecordCount(strWhere.ToString(), keyWords, start, end);
            return Json(ListResult(list, recordCount));
        }

    }
}

Sykj.Web/Areas/Manager/Views/Member/Index.cshtml
@{
    ViewData["Title"] = "会员管理";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">会员信息</div>
                <div class="layui-card-body">
                    <div class="layui-form">
                        <div class="layui-row">
                            <div class="layui-form-item">
                                <div class="layui-col-md3" style="padding-left:0">
                                    <div class="input-group">
                                        <input type="text" id="keyWords" name="keyWords" placeholder="请输入用户名称" autocomplete="off" class="layui-input">
                                        <span class="input-group-btn">
                                            <button class="layui-btn" id="search">
                                                <i class="layui-icon layui-icon-search"></i>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <div class="layui-btn-container">
                            <div class="layui-btn-group">
                                <button class="layui-btn layui-btn-sm" id="StartUsing"><i class="layui-icon layui-icon-ok"></i>启用</button>
                                <button class="layui-btn layui-btn-sm layui-btn-danger" id="Forbidden"><i class="layui-icon layui-icon-close"></i>禁用</button>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <table class="layui-table " lay-data="{page:true, id:'list'}" lay-filter="list">
                            <thead>
                                <tr>
                                    <th lay-data="{checkbox:true, fixed: true,style:'height:80px;'}"></th>
                                    <th lay-data="{ field: 'userId',width:80}">用户Id</th>
                                    <th lay-data="{ field: 'gravatar',templet:'#gravatar',style:'height:80px;padding:0 0',width:140}">用户头像</th>
                                    <th lay-data="{ field: 'userName',width:130}">用户名</th>
                                    <th lay-data="{ field: 'trueName',width:130}">姓名</th>
                                    <th lay-data="{ field: 'sex',templet:'#sex',align:'center',width:100}">性别</th>
                                    <th lay-data="{ field: 'points',width:100}">积分</th>
                                    <th lay-data="{ field: 'balance',width:100}">余额</th>
                                    <th lay-data="{ field: 'createDate',width:200}">注册时间</th>
                                    <th lay-data="{ field: 'activity',templet:'#activity',width:90}">状态</th>
                                    <th lay-data="{toolbar:'#tableoption'}">操作</th>
                                </tr>
                            </thead>
                        </table>
                        <script type="text/html" id="activity">
                            {{#  if(d.activity==true){  }}
                            <span class="layui-badge layui-bg-green">启用</span>
                            {{#  } else if(d.activity==false){ }}
                            <span class="layui-badge layui-bg-red">禁用</span>
                            {{#  } }}
                        </script>
                        <script type="text/html" id="gravatar">
                            {{#  if(d.gravatar.indexOf("http")!=-1){  }}
                            <div style="height:65px;"><img src="{{ d.gravatar }}" /></div>
                            {{#  } else if(d.gravatar.length<1){ }}
                            <div style="height:65px;"></div>
                            {{#  }else { }}
                            <div style="height:65px;"><img src="@BaseConfig.ImagesDoMain{{ d.gravatar }}" /></div>
                            {{#  } }}
                        </script>
                        <script type="text/html" id="tableoption">
                            <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="info"><i class="layui-icon">&#xe63c;</i>查看</a>
                        </script>
                        <script type="text/html" id="sex">
                            {{#  if(d.sex=='男'){  }}
                            <input type="checkbox" name="sex" checked value="{{d.userId}}" lay-skin="switch" lay-filter="switchSex" lay-text="男|女">
                            {{#  } else { }}
                            <input type="checkbox" name="sex" value="{{d.userId}}" lay-skin="switch" lay-filter="switchSex" lay-text="男|女">
                            {{#  } }}
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .layui-table-cell{
        height:100%
    }
</style>
@section scriptsfeet
{
<script type="text/javascript">
        layui.config({
            base: '/layuiadmin/' //自定义模块路径
        }).use(['sykjwh', 'table','form'], function () {
            var $ = layui.$, sykjwh = layui.sykjwh, table = layui.table,form=layui.form;

            //绑定数据
            sykjwh.dataBind('@Url.Action("List", "Member", new { area = Constant.AREAMANAGER })');

            //启用
            $("#StartUsing").click(function () {
                sykjwh.batOperate('@Url.Action("StartUsing", "Member", new { area = Constant.AREAMANAGER })', 'userId');
            });

            //禁用
            $("#Forbidden").click(function () {
                console.log("--------");
                sykjwh.batOperate('@Url.Action("Forbidden", "Member", new { area = Constant.AREAMANAGER })', 'userId');
            });

            form.on('switch(switchSex)', function (data) {
                //获取id值
                console.log(data.value + "----"); //开关value值，也可以通过data.elem.value得到
                var sex=this.checked?'男':'女'; 
                sykjwh.request("@Url.Action("SexEdit", "Member", new { area = Constant.AREAMANAGER })?userId=" + data.value + "&sex=" + sex,'POST');
            }); 

            //监听表格行
            table.on('tool(list)', function (obj) {
                var data = obj.data;//获得当前行数据
                if (obj.event === 'info') {
                    sykjwh.openFull('用户详情', '@Url.Action("Info", "Member", new { area = Constant.AREAMANAGER })/' + data.userId);
                } 
            });

            //搜索
            $("#search").click(function () {
                //绑定数据
                sykjwh.dataBind('@Url.Action("List", "Member", new { area = Constant.AREAMANAGER })', {
                    keyWords: $.trim($("#keyWords").val())
                });
            });
        });
</script>
}

Sykj.Web/Areas/Manager/Views/Member/Info.cshtml
@{
    ViewData["Title"] = "编辑用户扩展表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
@model Sykj.ViewModel.UserMember
<style>
    .layui-input {
        width: 55%;
        margin: 0,auto;
    }

    .layui-form-item {
        margin: 20px 0 20px 150px;
    }

    .layui-input-block > span {
        position: absolute;
        left: 57%;
        top: 10px;
    }

    .layui-form-select dl {
        min-width: 55%;
    }
</style>
<div class="layui-bgn" style="padding-bottom:150px;">
    <input type="hidden" asp-for="UserId" />
    <div class="layui-tab layui-tab-brief" style="margin-top:-3px;">
        <ul class="layui-tab-title">
            <li class="layui-this">基本信息</li>
            <li>扩展信息</li>
            <li>会员信息</li>
        </ul>
        <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <div class="layui-form-item" pane="">
                    <label class="layui-form-label">用户名</label>
                    <div class="layui-input-block">
                        <input type="text" lay-verify="required" readonly asp-for="UserName" name="UserName" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">头像</label>
                    <div class="layui-input-block">
                        @if (Model.Gravatar.StartsWith("http"))
                        {
                            <img style="width:100px;height:100px;" src="@Model.Gravatar" />
                        }
                        else if (Model.Gravatar.Length < 1)
                        {
                            <img style="width:100px;height:100px;" />
                        }
                        else
                        {
                            <img style="width:100px;height:100px;" src="@BaseConfig.ImagesDoMain@Model.Gravatar" />
                        }
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">昵称</label>
                    <div class="layui-input-block">
                        <input type="text" asp-for="NickName" readonly name="NickName" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">真实姓名</label>
                    <div class="layui-input-block">
                        <input type="text" asp-for="TrueName" readonly name="TrueName" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">性别</label>
                    <div class="layui-input-block">
                        <input type="text" asp-for="Sex" readonly name="Sex" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">手机号</label>
                    <div class="layui-input-block">
                        <input type="text" asp-for="Phone" readonly name="Phone" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">邮箱</label>
                    <div class="layui-input-block">
                        <input type="text" asp-for="Email" readonly name="Email" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">注册时间</label>
                    <div class="layui-input-block">
                        <input type="text" lay-verify="required" readonly name="CreateDate" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">是否通过实名认证</label>
                    <div class="layui-input-block">
                        <input name="IsUserDPI" id="IsUserDPI" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">用户状态</label>
                    <div class="layui-input-block">
                        <input type="text" lay-verify="required" readonly name="Activity" id="Activity" autocomplete="off" class="layui-input">
                    </div>
                </div>
            </div>
            <div class="layui-tab-item">
                <div class="layui-form-item">
                    <label class="layui-form-label">主页</label>
                    <div class="layui-input-block">
                        <input name="HomePage" id="HomePage" readonly asp-for="HomePage" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">个性签名</label>
                    <div class="layui-input-block">
                        <input name="Singature" id="Singature" readonly asp-for="Singature" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">QQ</label>
                    <div class="layui-input-block">
                        <input name="QQ" id="QQ" asp-for="QQ" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">住址</label>
                    <div class="layui-input-block">
                        <input name="Address" id="Address" readonly asp-for="Address" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">注册渠道</label>
                    <div class="layui-input-block">
                        <input name="SourceType" id="SourceType" readonly asp-for="SourceType" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">身份证号</label>
                    <div class="layui-input-block">
                        <input name="CardId" id="CardId" asp-for="CardId" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">备注</label>
                    <div class="layui-input-block">
                        <input name="Remark" id="Remark" asp-for="Remark" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">生日</label>
                    <div class="layui-input-block">
                        <input name="Birthday" id="Birthday" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">籍贯</label>
                    <div class="layui-input-block">
                        <input name="NativePlace" id="NativePlace" asp-for="NativePlace" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">电话号码</label>
                    <div class="layui-input-block">
                        <input name="TelPhone" id="TelPhone" asp-for="TelPhone" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">最后登录时间</label>
                    <div class="layui-input-block">
                        <input name="LastLoginDate" id="LastLoginDate" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
            </div>
            <div class="layui-tab-item">
                <div class="layui-form-item">
                    <label class="layui-form-label">等级</label>
                    <div class="layui-input-block">
                        <input name="Grade" id="Grade" asp-for="Grade" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">账户余额</label>
                    <div class="layui-input-block">
                        <input name="Balance" id="Balance" asp-for="Balance" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">积分</label>
                    <div class="layui-input-block">
                        <input name="Points" id="Points" asp-for="Points" readonly autocomplete="off" class="layui-input">
                    </div>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">会员卡</label>
                    <div class="layui-input-block">
                        <input name="UserCardCode" id="UserCardCode" readonly asp-for="UserCardCode" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">会员卡类型</label>
                    <div class="layui-input-block">
                        <input name="UserCardType" id="UserCardType" readonly asp-for="UserCardType" autocomplete="off" class="layui-input">
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-form-item" style="margin-left:30%">
            <button id="close" type="button" class="layui-btn layui-btn-primary">返回</button>
        </div>
    </div>
</div>
@section scriptsfeet
{
    <script type="text/javascript">
        layui.config({
            base: '/layuiadmin/' //静态资源所在路径;
        }).use(['form', 'sykjwh', 'element', 'util'], function () {

            var $ = layui.$, form = layui.form, sykjwh = layui.sykjwh,util=layui.util;

            $("#close").click(function () {
                sykjwh.close();
            });

            initInfo();

            function initInfo() {
                $("#IsUserDPI").val('@Model.IsUserDPI' == 'True' ? '是' : '否');
                $("#Activity").val('@Model.Activity' == 'True' ? '启用' : '禁用');

                //格式化日期
                if ('@Model.CreateDate' != '') {
                    $("#CreateDate").attr("value", util.toDateString('@Model.CreateDate', "yyyy-MM-dd"));
                }
                if ('@Model.Birthday' != '') {
                    $("#Birthday").attr("value", util.toDateString('@Model.Birthday', "yyyy-MM-dd"));
                }
                if ('@Model.LastLoginDate' != '') {
                    $("#LastLoginDate").attr("value", util.toDateString('@Model.LastLoginDate', "yyyy-MM-dd"));
                }
            }
        });
    </script>
}

Sykj.Web/Areas/Manager/Views/Member/PointsDetail.cshtml
@{
    ViewData["Title"] = "积分明细列表";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">积分明细</div>
                <div class="layui-card-body">
                    <div class="layui-form">
                        <div class="layui-row">
                            <div class="layui-form-item">
                                <div class="layui-col-md2" style="padding-left:0">
                                    <input id="Start" lay-filter="Start" class="layui-input" placeholder="起始时间"  />
                                </div>
                                <div class="layui-col-md2" style="padding-left:0">
                                    <input id="End" lay-filter="End" class="layui-input"  placeholder="结束时间" />
                                </div>
                                <div class="layui-col-md3">
                                    <div class="input-group">
                                        <input type="text" id="keyWords" name="keyWords" placeholder="请输入用户名称" autocomplete="off" class="layui-input">
                                        <span class="input-group-btn">
                                            <button class="layui-btn" id="search">
                                                <i class="layui-icon layui-icon-search"></i>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-row">
                        <table class="layui-table" lay-data="{page:true, id:'list'}" lay-filter="list">
                            <thead>
                                <tr>
                                    <th lay-data="{checkbox:true, fixed: true}"></th>
                                    <th lay-data="{ field: 'createdDate',width:250}">创建时间</th>
                                    <th lay-data="{ field: 'userId',width:120}"> 用户Id</th>
                                    <th lay-data="{ field: 'score',width:120}">影响分数</th>
                                    <th lay-data="{ field: 'type',templet:'#type',width:120}">类型</th>
                                    <th lay-data="{ field: 'description'}">积分描述</th>
                                </tr>
                            </thead>
                        </table>
                        <script type="text/html" id="type">
                            {{#  if(d.type==0){  }}
                            <span class="layui-badge layui-bg-green">获得积分</span>
                            {{#  } else if(d.type==1){ }}
                            <span class="layui-badge layui-bg-orange">消费积分</span>
                            {{#  } }}
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scriptsfeet
    {
    <script type="text/javascript">
        layui.config({
            base: '/layuiadmin/' //自定义模块路径
        }).use(['sykjwh', 'table', 'laydate'], function () {
            var $ = layui.$, sykjwh = layui.sykjwh, table = layui.table, laydate = layui.laydate;

            //绑定数据
            sykjwh.dataBind('@Url.Action("PointsDetailList", "Member", new { area = Constant.AREAMANAGER })');

            //搜索
            $("#search").click(function () {
                //绑定数据
                sykjwh.dataBind('@Url.Action("PointsDetailList", "Member", new { area = Constant.AREAMANAGER })', {
                    keyWords: $.trim($("#keyWords").val()),
                    start: $.trim($("#Start").val()),
                    end: $.trim($("#End").val())
                });
            });

            //日期
            laydate.render({
                elem: '#Start'
            });
            laydate.render({
                elem: '#End'
            });

        });
    </script>
}